spring:
  ## 줄 맞추기용 여백
  ##
  datasource:
    url: jdbc:postgresql://192.168.20.51:5432/dsket
    username: dsket
    password: Utltmxpa123@
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    root: info
    web: info
    sql: info